spring:
  datasource:
    username: root
    password: sukun031015
    url: jdbc:mysql:///imrms?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8080

sa-token:
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  token-style: uuid
  is-log: false

logging:
  level:
    com.imrms.com.imrms.intelligent_meeting_room: DEBUG

BaiduAip:
  appId: ENC(2IoCyGnxO2OqNuAKCsW/JwCVmOqZNAtYx/qqKzWIV+EdfLqn7aReli2SpFxQqNX0)
  apiKey: ENC(WOdujdaYBMVIkFXdShlCjMxQdtlxZ/nD+ttPhWKG4M8FP5iJ/jyRZb7fTQuiyedZy7h+yrzfz6jA9UxAEHZ8EQ==)
  secretKey: ENC(sjeAIiu+VYoz//q9oqFz95Z0rcIiSXTRK5GBcwm2cOsH7aEO2RgNtnEpo+3xJWFficGxSU7cIaT1ns4vIB4K2G1ktaoTcVJ68SqXUub4vl8=)